# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: 
    cp deploy.yml $(Build.ArtifactStagingDirectory)/deploy.yml
  displayName: 'Copy deployment files to artifacts'

- script: 
    cp service.yml $(Build.ArtifactStagingDirectory)/service.yml
  displayName: 'Copy service files to artifacts'

- script: |
    echo See art catalog:
    ls $(Build.ArtifactStagingDirectory)
  displayName: 'Check files'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'