apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-deployment
  labels:
    app: mario
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mario
  template:
    metadata:
      labels:
        app: mario
    spec:
      containers:
      - name: mario
        image: pengbai/docker-supermario
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mario-service
spec:
  selector:
    app: mario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
